//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TryItPage.WordCountService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WordCountService.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CountOccurrences", ReplyAction="http://tempuri.org/IService1/CountOccurrencesResponse")]
        int CountOccurrences(string inputStr, string pattern);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CountOccurrences", ReplyAction="http://tempuri.org/IService1/CountOccurrencesResponse")]
        System.Threading.Tasks.Task<int> CountOccurrencesAsync(string inputStr, string pattern);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/WordCount", ReplyAction="http://tempuri.org/IService1/WordCountResponse")]
        string WordCount(string textFile);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/WordCount", ReplyAction="http://tempuri.org/IService1/WordCountResponse")]
        System.Threading.Tasks.Task<string> WordCountAsync(string textFile);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : TryItPage.WordCountService.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<TryItPage.WordCountService.IService1>, TryItPage.WordCountService.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int CountOccurrences(string inputStr, string pattern) {
            return base.Channel.CountOccurrences(inputStr, pattern);
        }
        
        public System.Threading.Tasks.Task<int> CountOccurrencesAsync(string inputStr, string pattern) {
            return base.Channel.CountOccurrencesAsync(inputStr, pattern);
        }
        
        public string WordCount(string textFile) {
            return base.Channel.WordCount(textFile);
        }
        
        public System.Threading.Tasks.Task<string> WordCountAsync(string textFile) {
            return base.Channel.WordCountAsync(textFile);
        }
    }
}
